### ISSUE TITLE
Filter Repos by Modloader

### ISSUE THREAD

**Issue by AmyMialee** [Mycelium-Mod-Network/SpookyJam-Site#2]
And of course including an option for "not a mod" for stuff like this site

**Comment by Darkhax** [comment]
I forgot that this issue was originally intended for [Modtoberfest](https://github.com/Mycelium-Mod-Network/Modtoberfest-Site)  and added it to this data to our API lol

The modtoberfest site will be getting a few updates this year and hopefully this will be added.
